name: vedema
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^0.13.3
  logger: ^1.1.0
  cupertino_icons: ^1.0.8
  speech_to_text: 7.0.0
  permission_handler: ^11.0.1
  collection: ^1.18.0
  pie_chart: ^5.3.2
  syncfusion_flutter_charts: ^29.1.41
  syncfusion_flutter_core: ^29.1.41
  pdf: ^3.10.0
  printing: ^5.10.0
  path_provider: ^2.0.14
  fl_chart: ^0.63.0
  excel: ^2.0.1
  file_saver: ^0.2.14
  open_filex: ^4.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/logo.png
    - assets/home.png
    - assets/field.png
    - assets/stats.png
    - assets/location.png
    - assets/size.png
    - assets/leaf.png
    - assets/irrigation.png
    - assets/moreicon.png
    - assets/spraying.png
    - assets/fertilize.png
    - assets/irrigationg.png
    - assets/moreicong.png
    - assets/sprayingg.png
    - assets/fertilizeg.png
    - assets/menuicon.png
    - assets/microphone.png
    - assets/delete.png
    - assets/filters.png
    - assets/expensesfooter.png
    - assets/grinder.png
    - assets/sack.png
    - assets/grinderg.png
    - assets/sackg.png
    - assets/edit.png
