name: vedema
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  logger: ^1.1.0
  cupertino_icons: ^1.0.8
  speech_to_text: 7.0.0
  permission_handler: ^11.0.1
  collection: ^1.18.0
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/home.png
    - assets/field.png
    - assets/stats.png
    - assets/location.png
    - assets/size.png
    - assets/leaf.png
    - assets/irrigation.png
    - assets/moreicon.png
    - assets/spraying.png
    - assets/fertilize.png
    - assets/irrigationg.png
    - assets/moreicong.png
    - assets/sprayingg.png
    - assets/fertilizeg.png
    - assets/menuicon.png
    - assets/microphone.png
    - assets/delete.png
    - assets/filters.png
    - assets/expensesfooter.png
